name: Build Plugin

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn package -f ShardsEconomy/pom.xml
      - uses: actions/upload-artifact@v4
        with:
          name: ShardsEconomy
          path: ShardsEconomy/target/ShardsEconomy-1.0.0.jar
